version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: backend:latest
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    ports:
      - 8000:80
  static:
    image: nginx:alpine
    ports:
      - 8008:80
    volumes:
      - ./backend/static:/srv/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
